const PLACES = [
  // North
  ['Kashmir Valley','Jammu & Kashmir','North','mountains|nature','Winter snow, spring blooms and valley drives','Srinagar • Gulmarg • Pahalgam',9000,4.8,'budget','Kashmir'],
  ['Srinagar','Jammu & Kashmir','North','nature|spiritual','Dal Lake mornings, old-city lanes and gardens','Dal Lake • Mughal Gardens',3500,4.8,'budget','Srinagar'],
  ['Gulmarg','Jammu & Kashmir','North','mountains|adventure','Snow, meadows and Himalayan views','Gondola • Khilanmarg',5500,4.9,'smart','Gulmarg'],
  ['Leh','Ladakh','North','mountains|adventure','High-altitude landscapes, monasteries and stark roads','Shanti Stupa • Khardung area',6500,4.9,'smart','Leh'],
  ['Spiti Valley','Himachal Pradesh','North','mountains|adventure','Cold desert villages, monasteries and dramatic roads','Kaza • Key • Langza',7000,4.8,'smart','Spiti'],
  ['Manali','Himachal Pradesh','North','mountains|adventure','Classic mountain base with cafes, trails and river views','Old Manali • Solang',4500,4.7,'smart','Manali'],
  ['Tirthan Valley','Himachal Pradesh','North','nature|mountains','Quiet villages, forest trails and river-side stays','Jibhi • Great Himalayan edge',4200,4.7,'smart','Tirthan'],
  ['Kasol','Himachal Pradesh','North','mountains|adventure','Backpacker base for Parvati Valley trails','Chalal • Tosh route',3000,4.6,'budget','Kasol'],
  ['Rishikesh','Uttarakhand','North','adventure|spiritual','Ganga ghats, yoga, cafes and rafting','Laxman Jhula area • Riverfront',3000,4.7,'budget','Rishikesh'],
  ['Auli','Uttarakhand','North','mountains|adventure','Alpine meadows with big Himalayan horizons','Auli slopes • Joshimath',6000,4.8,'smart','Auli'],
  ['Mussoorie','Uttarakhand','North','mountains|food','Old hill-station charm, viewpoints and cafes','Mall Road • Landour',3500,4.5,'budget','Mussoorie'],
  ['Chopta','Uttarakhand','North','mountains|adventure','A compact Himalayan trekking base','Tungnath • Chandrashila',4200,4.8,'budget','Chopta'],
  ['Jaipur','Rajasthan','North','heritage|food','Palaces, bazaars, block prints and Rajasthani food','Amber Fort • City Palace',3500,4.8,'budget','Jaipur'],
  ['Jodhpur','Rajasthan','North','heritage|food','Blue lanes under one enormous fort','Mehrangarh • Old City',3200,4.8,'budget','Jodhpur'],
  ['Udaipur','Rajasthan','North','heritage|food','Lakes, havelis and sunset walks','City Palace • Lake Pichola',4200,4.8,'smart','Udaipur'],
  ['Jaisalmer','Rajasthan','North','heritage|adventure','Golden fort and desert camp country','Fort • Sam dunes',5000,4.7,'smart','Jaisalmer'],
  ['Pushkar','Rajasthan','North','spiritual|heritage|food','Lake-side lanes, temples and desert-town energy','Pushkar Lake • Savitri hill',2500,4.5,'budget','Pushkar'],
  ['Delhi','Delhi','North','heritage|food','Historic layers, street food and giant monuments','Old Delhi • Humayun area',2800,4.6,'budget','Delhi'],
  ['Amritsar','Punjab','North','spiritual|food|heritage','Golden Temple serenity and legendary food','Golden Temple • Old market',3000,4.8,'budget','Amritsar'],
  ['Lucknow','Uttar Pradesh','North','food|heritage','Awadhi food, old architecture and elegant ruins','Bara Imambara • Chowk',3000,4.6,'budget','Lucknow'],
  ['Agra','Uttar Pradesh','North','heritage','The Taj, Mughal architecture and riverside history','Taj Mahal • Agra Fort',3000,4.7,'budget','Agra'],
  ['Varanasi','Uttar Pradesh','North','spiritual|food','Ganga ghats, old lanes, music and sunrise boats','Dashashwamedh • Assi',2800,4.8,'budget','Varanasi'],
  ['Khajuraho','Madhya Pradesh','Central','heritage','Sculpted temples, cycling and a slower town','Western Group • Old town',2800,4.7,'budget','Khajuraho'],
  ['Orchha','Madhya Pradesh','Central','heritage|spiritual','Palaces and temples on the Betwa River','Orchha Fort • Cenotaphs',2500,4.7,'budget','Orchha'],
  // West
  ['Goa','Goa','West','beach|food','Beaches, Portuguese quarters, cafes and sunsets','Panaji • South Goa',5500,4.7,'smart','Goa'],
  ['Gokarna','Karnataka','West','beach|spiritual','Temple town energy with walkable beaches','Om • Kudle • Half Moon',3500,4.7,'budget','Gokarna'],
  ['Hampi','Karnataka','West','heritage|adventure','Ruins, boulders, sunrise and bike rides','Vijayanagara • Hemakuta',3200,4.9,'budget','Hampi'],
  ['Mumbai','Maharashtra','West','food|heritage','Sea, street food, art deco and night energy','Fort • Marine Drive',4500,4.6,'smart','Mumbai'],
  ['Pune','Maharashtra','West','food|heritage','Cafes, hills and a rich local history','Shaniwar Wada • Parvati',2800,4.5,'budget','Pune'],
  ['Alibaug','Maharashtra','West','beach|food','Quick coastal escape from the city','Kihim • Fort',4000,4.5,'smart','Alibaug'],
  ['Diu','Dadra and Nagar Haveli and Daman and Diu','West','beach|heritage','Quiet coast, Portuguese-era streets and fort walls','Diu Fort • Naida caves',3200,4.5,'budget','Diu'],
  ['Kutch','Gujarat','West','heritage|nature','Salt desert, craft villages and big skies','Rann • Bhuj',5500,4.7,'smart','Kutch'],
  ['Ahmedabad','Gujarat','West','heritage|food','Pol houses, stepwells and serious food','Old City • Adalaj',3000,4.6,'budget','Ahmedabad'],
  ['Dwarka','Gujarat','West','spiritual|heritage','Temple town on the Arabian Sea','Dwarkadhish • Coast',3200,4.6,'budget','Dwarka'],
  // South
  ['Munnar','Kerala','South','nature|mountains','Tea hills, misty roads and waterfalls','Tea gardens • Top Station',4500,4.8,'smart','Munnar'],
  ['Alappuzha','Kerala','South','nature|food','Backwaters, village life and slow boats','Backwaters • Beach',4200,4.8,'smart','Alappuzha'],
  ['Varkala','Kerala','South','beach|food','Cliff-top coast, cafes and evening light','Varkala cliff • Beach',3500,4.7,'budget','Varkala'],
  ['Wayanad','Kerala','South','nature|adventure','Forests, waterfalls and spice-country drives','Edakkal • Soochipara',4200,4.7,'smart','Wayanad'],
  ['Kochi','Kerala','South','heritage|food','Colonial layers, art spaces and seafood','Fort Kochi • Mattancherry',3000,4.7,'budget','Kochi'],
  ['Ooty','Tamil Nadu','South','mountains|nature','Cool hills, tea and toy-train nostalgia','Coonoor • Botanical Garden',4000,4.5,'smart','Ooty'],
  ['Kodaikanal','Tamil Nadu','South','mountains|nature','Pines, lake walks and cool weather','Coaker’s Walk • Lake',3800,4.6,'smart','Kodaikanal'],
  ['Rameswaram','Tamil Nadu','South','spiritual|beach','Pilgrimage, sea bridges and island roads','Ramanathaswamy • Pamban',3200,4.6,'budget','Rameswaram'],
  ['Madurai','Tamil Nadu','South','spiritual|food|heritage','Temple towers and night markets','Meenakshi Temple • Old city',2500,4.7,'budget','Madurai'],
  ['Puducherry','Puducherry','South','beach|food|heritage','French-era streets, cafes and coastal cycling','White Town • Promenade',3500,4.7,'budget','Puducherry'],
  ['Hampi South Trail','Karnataka','South','heritage|adventure','A quieter approach to the ruins and river landscape','Anegundi • Sanapur',3000,4.7,'budget','Anegundi'],
  ['Coorg','Karnataka','South','nature|food','Coffee estates, forest roads and homestays','Madikeri • Abbey Falls',4200,4.7,'smart','Coorg'],
  ['Chikmagalur','Karnataka','South','nature|mountains','Coffee country and highland drives','Mullayanagiri • Estates',4000,4.7,'smart','Chikmagalur'],
  ['Ooty village loop','Tamil Nadu','South','nature|mountains','Small tea-country hamlets beyond the tourist core','Lovedale • Coonoor',3200,4.5,'budget','Ooty village'],
  ['Andaman Islands','Andaman & Nicobar Islands','South','beach|adventure','Clear-water beaches, forests and island time','Swaraj Dweep • Port Blair',12000,4.8,'premium','Andaman'],
  // East
  ['Darjeeling','West Bengal','East','mountains|food','Tea, toy trains and Kanchenjunga views','Tiger Hill • Chowrasta',4500,4.7,'smart','Darjeeling'],
  ['Sikkim','Sikkim','East','mountains|nature','Monasteries, high passes and mountain villages','Gangtok • Tsomgo area',6000,4.8,'smart','Sikkim'],
  ['Pelling','Sikkim','East','mountains|nature','Quiet mountain views and monasteries','Pemayangtse • Skywalk',4800,4.7,'smart','Pelling'],
  ['Meghalaya','Meghalaya','East','nature|adventure','Waterfalls, caves, clean hills and village trails','Shillong • Sohra',5500,4.8,'smart','Meghalaya'],
  ['Ziro Valley','Arunachal Pradesh','East','nature|food','Green valley, villages and low-key landscapes','Ziro • Hapoli',6500,4.7,'smart','Ziro'],
  ['Tawang','Arunachal Pradesh','East','mountains|spiritual','High mountain roads and a spectacular monastery','Monastery • Sela route',9000,4.8,'premium','Tawang'],
  ['Kaziranga','Assam','East','nature|adventure','Wildlife safari country and riverine landscapes','Central range • Tea country',6000,4.7,'smart','Kaziranga'],
  ['Majuli','Assam','East','culture|nature','River island life, satras and cycling','Satras • Village trails',3000,4.6,'budget','Majuli'],
  ['Kolkata','West Bengal','East','food|heritage','Books, trams, colonial architecture and food','Park Street • North Kolkata',3000,4.6,'budget','Kolkata'],
  ['Bhubaneswar','Odisha','East','heritage|spiritual','Temple city and gateway to Odisha’s coast','Old Town • Lingaraj',2800,4.6,'budget','Bhubaneswar'],
  ['Puri','Odisha','East','beach|spiritual','Jagannath culture with an easy beach rhythm','Temple • Golden Beach',3000,4.7,'budget','Puri'],
  ['Konark','Odisha','East','heritage|beach','Sun Temple and coastal day trip','Sun Temple • Chandrabhaga',2600,4.7,'budget','Konark'],
  // North East / Central extra
  ['Shillong','Meghalaya','North-East','nature|food','Hill-city cafes with waterfalls close by','Police Bazar • Laitlum',3500,4.6,'budget','Shillong'],
  ['Cherrapunji','Meghalaya','North-East','nature|adventure','Living root bridges and huge monsoon landscapes','Sohra • Nongriat',4500,4.8,'smart','Cherrapunji'],
  ['Mawlynnong','Meghalaya','North-East','nature','A tiny village for clean lanes and views','Village • Sky View',3200,4.6,'budget','Mawlynnong'],
  ['Kohima','Nagaland','North-East','culture|nature','Hills, food and war-history trails','Kisama • War Cemetery',4000,4.6,'smart','Kohima'],
  ['Dzukou Valley','Nagaland','North-East','mountains|adventure','Bucket-list trekking through open highlands','Dzukou trek',4500,4.8,'smart','Dzukou'],
  ['Mizoram road trip','Mizoram','North-East','mountains|culture','Long roads, small towns and dramatic ridges','Aizawl • Hmuifang',6000,4.6,'smart','Mizoram'],
  ['Gangtok','Sikkim','North-East','mountains|food','Compact Himalayan city with monastery and lake day trips','MG Marg • Rumtek',4200,4.7,'smart','Gangtok'],
  ['Imphal','Manipur','North-East','culture|nature','Valleys, markets and a different Northeast rhythm','Kangla • Loktak day trip',4000,4.5,'smart','Imphal'],
  ['Bastar','Chhattisgarh','Central','nature|culture','Waterfalls, forests and village craft traditions','Chitrakote • Jagdalpur',4500,4.6,'smart','Bastar'],
  ['Jabalpur','Madhya Pradesh','Central','nature|heritage','Marble rocks and monsoon waterfalls','Bhedaghat • Dhuandhar',2600,4.7,'budget','Jabalpur'],
  ['Pachmarhi','Madhya Pradesh','Central','nature|mountains','Satpura hills, caves and forest roads','Bee Fall • Sunset Point',3000,4.6,'budget','Pachmarhi'],
  ['Bhopal','Madhya Pradesh','Central','heritage|food','Lakes, museums and old-city food','Upper Lake • Sanchi day trip',2800,4.5,'budget','Bhopal'],
  ['Sanchi','Madhya Pradesh','Central','heritage|spiritual','One of India’s great Buddhist heritage landscapes','Stupa • Vidisha',2200,4.7,'budget','Sanchi'],
  ['Satpura','Madhya Pradesh','Central','nature|adventure','Forest stays and wildlife without the big-city feel','Tiger reserve region',7000,4.7,'smart','Satpura'],
  ['Gwalior','Madhya Pradesh','Central','heritage','A hill fort above a deeply historic city','Gwalior Fort • Old city',2500,4.6,'budget','Gwalior'],
  ['Bundi','Rajasthan','North','heritage|food','Blue lanes, painted palace walls and a slower Rajasthan','Garh Palace • Stepwells',2600,4.7,'budget','Bundi'],
  ['Mandawa','Rajasthan','North','heritage','Havelis and frescoes in Shekhawati villages','Havelis • Old lanes',2400,4.5,'budget','Mandawa'],
  ['Dausa villages','Rajasthan','North','heritage|culture','A rural gateway for stepwells and temple landscapes','Abhaneri • Rural lanes',2400,4.5,'budget','Dausa'],
  ['Sundarbans','West Bengal','East','nature|adventure','Mangroves, boats and a wild-edge landscape','Sajnekhali • Boat safari',6500,4.7,'smart','Sundarbans'],
  ['Havelock beaches','Andaman & Nicobar Islands','South','beach|adventure','Island beaches and snorkelling days','Radhanagar • Elephant Beach',11000,4.8,'premium','Havelock'],
  ['Dhanaulti','Uttarakhand','North','mountains|nature','Forest escape near Mussoorie without the same crowd','Eco park • Forest',3000,4.5,'budget','Dhanaulti']
].map((p,i)=>({id:i+1,name:p[0],state:p[1],region:p[2],vibes:p[3].split('|'),desc:p[4],spots:p[5],budget:p[6],rating:p[7],tier:p[8],q:p[9]}));

const SEASONS = {
  1:{name:'Winter',copy:'Best for the plains, Rajasthan, heritage circuits and most of South India. Snow destinations are in their dramatic season.',fav:['heritage','food','beach','spiritual'],accent:'#b24c2d',accent2:'#d08a3b'},
  2:{name:'Winter → Spring',copy:'A sweet-spot month for Rajasthan, Kerala, Goa and much of the North before peak heat.',fav:['heritage','beach','food','nature'],accent:'#b24c2d',accent2:'#c08f3f'},
  3:{name:'Spring',copy:'Hills start pulling ahead. Think Kashmir blooms, Northeast greenery and cooler highlands.',fav:['mountains','nature','adventure'],accent:'#7c6543',accent2:'#9bb06e'},
  4:{name:'Spring → Summer',copy:'Plains get hot. Move upward: Himachal, Uttarakhand, Northeast and hill stations.',fav:['mountains','nature','adventure'],accent:'#4c6a55',accent2:'#bba45b'},
  5:{name:'Summer',copy:'Highlands win. Choose mountains, tea country and Northeast instead of fighting the heat in the plains.',fav:['mountains','nature','adventure'],accent:'#486653',accent2:'#d39a45'},
  6:{name:'Monsoon begins',copy:'Rain-fed landscapes wake up. Kerala, Meghalaya and some Western Ghats routes become cinematic.',fav:['nature','adventure','food'],accent:'#356b5a',accent2:'#7e9e69'},
  7:{name:'Monsoon',copy:'Waterfalls, green valleys and cloud-heavy landscapes. Build flexible days and expect transport delays.',fav:['nature','adventure'],accent:'#2f6254',accent2:'#5d9275'},
  8:{name:'Monsoon',copy:'Peak green season. Northeast and Western Ghats look unreal, while mountain-road plans need flexibility.',fav:['nature','adventure'],accent:'#3c6b5c',accent2:'#8aa66c'},
  9:{name:'Late Monsoon',copy:'A transition month: lush nature, fewer crowds in many places, and easier planning than peak monsoon.',fav:['nature','food','heritage'],accent:'#4b6852',accent2:'#c37b45'},
  10:{name:'Autumn',copy:'One of India’s strongest travel months. Great for heritage cities, Rajasthan, mountains and festive routes.',fav:['heritage','food','mountains','spiritual'],accent:'#9f522d',accent2:'#d18d3d'},
  11:{name:'Autumn → Winter',copy:'Excellent all-rounder month. Rajasthan and North India shine while South India stays inviting.',fav:['heritage','food','beach','nature'],accent:'#a74d2c',accent2:'#ce8c3e'},
  12:{name:'Winter',copy:'Golden season for Rajasthan, plains, Goa and heritage circuits. Himalayan snow routes return.',fav:['heritage','beach','food','mountains'],accent:'#93482d',accent2:'#b88652'}
};

let state={month:new Date().getMonth()+1,days:7,budget:10000,vibe:'all',tier:'all',regions:[],search:'',sort:'match',shown:9,selected:null,saved:JSON.parse(localStorage.getItem('t3_saved')||'[]')};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function money(n){return '₹'+n.toLocaleString('en-IN')}
function applyTheme(){const s=SEASONS[state.month];document.documentElement.style.setProperty('--accent',s.accent);document.documentElement.style.setProperty('--accent2',s.accent2);$('#seasonBanner').innerHTML=`<div class="season-inner"><div><span class="eyebrow">THIS MONTH</span><div class="season-title">${s.name}</div></div><div class="season-copy">${s.copy}</div></div>`;$('.season-glow').style.background=`radial-gradient(circle at 70% 30%,${s.accent2}36,transparent 60%),radial-gradient(circle at 20% 20%,${s.accent}26,transparent 55%)`}
function matchScore(p){const season=SEASONS[state.month];let score=0;score+=Math.max(0,18-Math.abs(p.budget-state.budget)/800);if(state.vibe==='all')score+=5;else if(p.vibes.includes(state.vibe))score+=24;else score-=8;if(season.fav.some(v=>p.vibes.includes(v)))score+=8;if(p.budget<=state.budget)score+=18;else score-=Math.min(18,(p.budget-state.budget)/900);if(state.tier==='budget'&&p.tier==='budget')score+=25;if(state.tier==='smart'&&p.tier!=='premium')score+=12;if(state.tier==='premium'&&p.tier==='premium')score+=25;if(state.tier==='all')score+=5;if(p.rating>=4.8)score+=5;return score}
function filtered(){let arr=PLACES.filter(p=>{const reg=!state.regions.length||state.regions.includes(p.region);const q=(p.name+' '+p.state+' '+p.desc+' '+p.spots).toLowerCase();const search=!state.search||q.includes(state.search.toLowerCase());const vibe=state.vibe==='all'||p.vibes.includes(state.vibe);const tier=state.tier==='all'||(state.tier==='budget'?p.budget<=5000:state.tier==='smart'?p.budget<=10000:p.budget>10000);return reg&&search&&vibe&&tier});arr.forEach(p=>p.score=matchScore(p));if(state.sort==='budget')arr.sort((a,b)=>a.budget-b.budget);else if(state.sort==='rating')arr.sort((a,b)=>b.rating-a.rating);else if(state.sort==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));else arr.sort((a,b)=>b.score-a.score);return arr}
function imageStyle(p){const palettes={heritage:['#803c2d','#d59c51'],nature:['#355d4d','#8aa76c'],beach:['#0b6674','#d59f61'],mountains:['#3e5061','#a79c7b'],food:['#8f492a','#d7a05a'],spiritual:['#5a4333','#c18a42'],adventure:['#384e4a','#a86b49'],culture:['#6e4f40','#b88a5b']};let v=p.vibes[0];let c=palettes[v]||palettes.heritage;return `background:linear-gradient(145deg,${c[0]},${c[1]})`}
function renderCards(){const arr=filtered();$('#resultCount').textContent=`${arr.length} places`;$('#resultsTitle').textContent=arr.length?`Good places for ${new Date(2026,state.month-1).toLocaleString('en',{month:'long'})}`:'Try a wider filter';const shown=arr.slice(0,state.shown);$('#placesGrid').innerHTML=shown.length?shown.map(p=>`<article class="place-card"><div class="place-visual" style="${imageStyle(p)}"><div class="tag-row"><span class="tag">${p.region.toUpperCase()}</span><span class="tag">${p.tier.toUpperCase()}</span></div><div class="place-initial">${p.name.split(' ').map(x=>x[0]).slice(0,2).join('')}</div></div><div class="place-body"><div class="place-top"><div><div class="place-title">${p.name}</div><div class="place-state">${p.state}</div></div><div class="rating">★ ${p.rating}</div></div><p class="place-desc">${p.desc}</p><div class="place-meta"><span class="meta-pill">from ${money(p.budget)}</span><span class="meta-pill">${p.spots}</span></div><div class="place-actions"><button class="build-btn" data-build="${p.id}">Build trip</button><a class="media-btn" target="_blank" rel="noopener" href="https://unsplash.com/s/photos/${encodeURIComponent(p.q+' India travel')}">Photos ↗</a></div></div></article>`).join(''):`<div class="no-results">Nothing fits that filter combination. Raise the budget, clear the vibe, or search a broader word.</div>`;$('#loadMoreBtn').style.display=state.shown>=arr.length?'none':'block'}
function updateMonthStrip(){const names=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];$('#monthStrip').innerHTML=names.map((n,i)=>`<button class="month-chip ${state.month===i+1?'active':''}" data-month="${i+1}">${n}</button>`).join('')}
function buildPlan(p){state.selected=p;const tier=state.budget<5000?'budget':state.budget<15000?'smart':'premium';const intensity=tier==='budget'?['slow','walkable','public transport']:tier==='smart'?['balanced','mixed transport','one paid experience']:['comfortable','private/fast transfer','curated experience'];const actions=[
  ['Arrive + orient','Check in, local breakfast and a low-friction walk around the core'],['Signature morning','Do the destination’s one unmissable landmark early, before the crowds'],['Local layer','Markets, lanes, village, craft or neighbourhood time'],['Nature / day trip','Pick the best nearby natural or scenic stop'],['Culture + food','Museum, temple, fort, cooking or a strong local meal'],['Free roam','Keep this day intentionally loose for a hike, cafe, beach or extra stop'],['Slow finish','Sunrise/sunset, favourite spot again, check out and depart']
];const rows=actions.slice(0,state.days).map((a,i)=>{const cost=Math.round((p.budget/state.days)*(i===0?1.15:i===6?.8:1));return `<div class="day-row"><div class="day-num">DAY ${i+1}</div><div><div class="day-title">${a[0]}</div><div class="day-desc">${a[1]} in <b>${p.name}</b>.</div><div class="day-tags"><span class="day-tag">${intensity[(i)%intensity.length]}</span><span class="day-tag">${i===0?'arrival':'flexible'}</span></div></div><div class="day-cost">~${money(cost)}</div></div>`}).join('');$('#selectedPlace').innerHTML=`<h3>${p.name}</h3><p>${p.state} • ${p.region} • ★ ${p.rating}</p><p>Starter trip budget: <b>${money(p.budget)}</b>. Your cap: <b>${money(state.budget)}</b>.</p>`;$('#planMeta').textContent=`${state.days} days • ${p.name} • ${money(state.budget)} cap`;$('#itinerary').innerHTML=rows;$('#saveTripBtn').disabled=false;$('#copyTripBtn').disabled=false;$('#plannerTitle').textContent=`${p.name}, your way.`;document.querySelector('#planner').scrollIntoView({behavior:'smooth',block:'start'})}
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>el.classList.remove('show'),2200)}
function sync(){applyTheme();updateMonthStrip();$('#monthSelect').value=state.month;$('#daysSelect').value=state.days;$('#budgetRange').value=state.budget;$('#budgetText').textContent=money(state.budget);$('#vibeSelect').value=state.vibe;$('#searchInput').value=state.search;$$('.tier-pill').forEach(b=>b.classList.toggle('active',b.dataset.tier===state.tier));$$('.region-check').forEach(c=>c.checked=state.regions.includes(c.value));renderCards();$('#savedCount').textContent=state.saved.length}
$$('.tier-pill').forEach(b=>b.addEventListener('click',()=>{state.tier=b.dataset.tier;state.shown=9;sync()}));
$$('.region-check').forEach(c=>c.addEventListener('change',()=>{state.regions=$$('.region-check:checked').map(x=>x.value);state.shown=9;renderCards()}));
$('#monthSelect').addEventListener('change',e=>{state.month=+e.target.value;state.shown=9;sync()});$('#daysSelect').addEventListener('change',e=>{state.days=+e.target.value;if(state.selected)buildPlan(state.selected);sync()});$('#budgetRange').addEventListener('input',e=>{state.budget=+e.target.value;$('#budgetText').textContent=money(state.budget);renderCards();if(state.selected)buildPlan(state.selected)});$('#vibeSelect').addEventListener('change',e=>{state.vibe=e.target.value;state.shown=9;renderCards()});$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;state.shown=9;renderCards()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderCards()});$$('.month-chip').forEach(()=>{});$('#monthStrip').addEventListener('click',e=>{const b=e.target.closest('[data-month]');if(!b)return;state.month=+b.dataset.month;state.shown=9;sync()});$('#placesGrid').addEventListener('click',e=>{const b=e.target.closest('[data-build]');if(!b)return;buildPlan(PLACES.find(p=>p.id==b.dataset.build))});$('#loadMoreBtn').addEventListener('click',()=>{state.shown+=9;renderCards()});$('#resetBtn').addEventListener('click',()=>{state={...state,month:new Date().getMonth()+1,days:7,budget:10000,vibe:'all',tier:'all',regions:[],search:'',sort:'match',shown:9};sync();toast('Filters reset')});$('#surpriseBtn').addEventListener('click',()=>{const arr=filtered();if(arr[0])buildPlan(arr[Math.floor(Math.random()*Math.min(arr.length,12))]);else toast('No places match these filters')});
$$('[data-set-tier]').forEach(b=>b.addEventListener('click',()=>{const t=b.dataset.setTier;state.tier=t;state.budget=t==='budget'?5000:t==='smart'?10000:30000;sync();document.querySelector('#explore').scrollIntoView({behavior:'smooth',block:'start'});toast(`${t[0].toUpperCase()+t.slice(1)} tier selected`)}));
$('#saveTripBtn').addEventListener('click',()=>{if(!state.selected)return;const item={place:state.selected.name,state:state.selected.state,days:state.days,budget:state.budget,month:state.month,savedAt:new Date().toISOString()};state.saved=[item,...state.saved.filter(x=>x.place!==item.place)].slice(0,20);localStorage.setItem('t3_saved',JSON.stringify(state.saved));sync();toast('Trip saved in this browser')});
$('#copyTripBtn').addEventListener('click',async()=>{if(!state.selected)return;const p=state.selected;const text=`ThreeTierTrips — ${p.name}\n${state.days} days • budget cap ${money(state.budget)}\n\n`+Array.from(document.querySelectorAll('.day-row')).map((r,i)=>`Day ${i+1}: ${r.querySelector('.day-title').textContent} — ${r.querySelector('.day-desc').textContent}`).join('\n');try{await navigator.clipboard.writeText(text);toast('Itinerary copied')}catch(e){toast('Copy blocked by browser')}});
$('#printBtn').addEventListener('click',()=>window.print());$('#savedBtn').addEventListener('click',()=>{if(!state.saved.length){toast('No saved trips yet');return}const names=state.saved.map(x=>x.place).join(' • ');toast('Saved: '+names)});
sync();
