const months=["January","February","March","April","May","June","July","August","September","October","November","December"];
const seasonInfo={January:["WINTER · INDIA","TRAVEL WARMER","Cool cities & mountain light","winter"],February:["WINTER · INDIA","FOLLOW THE LIGHT","Soft winter journeys","winter"],March:["SPRING · INDIA","CHASE SPRING","Wildlife & hills before the heat","summer"],April:["SUMMER · INDIA","HEAD HIGHER","Hill escapes & cool routes","summer"],May:["SUMMER · INDIA","FIND THE COOL","High altitude, forests, slow travel","summer"],June:["MONSOON · INDIA","FOLLOW THE RAIN","First rains & green roads","monsoon"],July:["MONSOON · INDIA","GO WHERE IT'S GREEN","Waterfalls & deep green","monsoon"],August:["MONSOON · INDIA","LET INDIA TURN GREEN","Peak lush-season routes","monsoon"],September:["SEPTEMBER · INDIA","TRAVEL SLOWLY","Green valleys, rain & quieter roads","monsoon"],October:["AUTUMN · INDIA","FOLLOW THE LIGHT","Post-monsoon road trips","autumn"],November:["AUTUMN · INDIA","TAKE THE LONG WAY","Clear skies & festive routes","autumn"],December:["WINTER · INDIA","END SOMEWHERE BEAUTIFUL","Winter journeys","winter"]};
const all=ITINERA_DATA.flatMap(s=>s.places);
const $=id=>document.getElementById(id);
let selectedPlace=null, selectedDays=7, activeTab="popular", atmo=true, calendarCursor=new Date(2026,8,1);
months.forEach(m=>$("month").add(new Option(m,m))); $("month").value="September";
ITINERA_DATA.forEach(s=>$("state").add(new Option(s.state,s.state)));
$("savedCount").textContent=JSON.parse(localStorage.getItem("itineraSaved")||"[]").length;
function money(n){return n>=100000?`₹${(n/100000).toFixed(1)}L`:n>=1000?`₹${Math.round(n/1000)}k`:`₹${n}`}
function placeById(id){return all.find(p=>p.id===id)}
function showView(v){document.querySelectorAll(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===v));document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(`view-${v}`).classList.add("active");if(v==="discover")renderPlaces();if(v==="saved")renderSaved();if(v==="atlas")renderAtlas();if(window.innerWidth<760)$("sidebar").classList.remove("open");}
document.querySelectorAll(".nav-item[data-view]").forEach(b=>b.onclick=()=>showView(b.dataset.view));
document.querySelectorAll("[data-viewlink]").forEach(b=>b.onclick=()=>showView(b.dataset.viewlink));
$("menuBtn").onclick=()=>$("sidebar").classList.toggle("open");
$("themeBtn")?.addEventListener("click",toggleTheme); // safe if future nav changes
document.querySelector('[data-action="theme"]').onclick=toggleTheme;
document.querySelector('[data-action="about"]').onclick=()=>toast("ITINERA is a season-aware India travel dashboard — created by RAHUL MAHTO.");
$("themeBtn")?.remove();
function toggleTheme(){document.body.classList.toggle("dark");$("themeIcon").textContent=document.body.classList.contains("dark")?"☀":"☾";localStorage.setItem("itineraDark",document.body.classList.contains("dark"))}
if(localStorage.getItem("itineraDark")==="true"){document.body.classList.add("dark");$("themeIcon").textContent="☀"}
function renderFeatured(){const picks=[...all].filter(p=>["Kashmir Valley","Sikkim","Meghalaya"].includes(p.name));$("featuredGrid").innerHTML=picks.map(p=>`<article class="featured"><div class="featured-img" style="background-image:url('${p.image}')"><span class="tag">${p.tag} · Sep</span></div><div class="featured-body"><h3>${p.name}</h3><p>${p.state} · ${p.duration}</p><div class="price-row"><span>from</span><b>${money(p.budget)}</b></div><button data-id="${p.id}">Explore place →</button></div></article>`).join("");$("featuredGrid").querySelectorAll("button").forEach(b=>b.onclick=()=>openPlace(+b.dataset.id))}
function renderCompact(){let list;if(activeTab==="budget")list=[...all].sort((a,b)=>a.budget-b.budget).slice(0,6);else if(activeTab==="green")list=[...all].filter(p=>p.tag==="green"||p.tag==="nature").slice(0,6);else list=[...all].sort((a,b)=>b.rating-a.rating).slice(0,6);$("compactGrid").innerHTML=list.map(p=>`<div class="compact" onclick="openPlace(${p.id})"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><small>${p.state}</small></div><div class="mini-price"><b>${money(p.budget)}</b>starter</div></div>`).join("")}
document.querySelectorAll("#homeTabs button").forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;document.querySelectorAll("#homeTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderCompact()});
function renderTrips(){let saved=JSON.parse(localStorage.getItem("itineraSaved")||"[]").slice(0,3);$("tripList").innerHTML=saved.length?saved.map(p=>`<div class="trip-item"><div class="trip-thumb" style="background-image:url('${p.image}')"></div><div><b>${p.name}</b><small>${p.state} · saved</small></div></div>`).join(""):`<div class="trip-item"><div class="trip-thumb" style="background-image:url('${all[0].image}')"></div><div><b>No saved trips yet</b><small>Open a place and tap Save.</small></div></div>`}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$("calTitle").textContent=months[m]+" "+y;const first=new Date(y,m,1).getDay(),max=new Date(y,m+1,0).getDate(),prevMax=new Date(y,m,0).getDate();let html="";for(let i=0;i<first;i++)html+=`<button class="muted">${prevMax-first+i+1}</button>`;for(let d=1;d<=max;d++)html+=`<button class="${d===new Date().getDate()&&y===new Date().getFullYear()&&m===new Date().getMonth()?"selected":""}">${d}</button>`;$("calendarDays").innerHTML=html}
$("prevMonth").onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()};$("nextMonth").onclick=()=>{calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()};
$("buildPromo").onclick=()=>{selectedPlace=null;$("planPlace").textContent="Choose a place";showView("planner")};
$("surpriseBtn").onclick=()=>openPlace(all[Math.floor(Math.random()*all.length)].id);
function renderPlaces(){const max=+$("budget").value,q=$("globalSearch").value.trim().toLowerCase(),state=$("state").value,v=$("vibe").value;let list=[...all];if(q)list=list.filter(p=>(p.name+" "+p.state).toLowerCase().includes(q));if(state)list=list.filter(p=>p.state===state);if(v!=="Anything")list=list.filter(p=>p.tag.toLowerCase().includes(v.toLowerCase())||p.name.toLowerCase().includes(v.toLowerCase()));if($("nature").checked)list=list.filter(p=>p.tag==="nature"||p.tag==="green");if($("culture").checked)list=list.filter(p=>p.tag==="culture");if($("low").checked)list=list.filter(p=>p.budget<5000);list=list.filter(p=>p.budget<=max);if($("sort").value==="low")list.sort((a,b)=>a.budget-b.budget);if($("sort").value==="rating")list.sort((a,b)=>b.rating-a.rating);$("budgetText").textContent=money(max);$("resultCount").textContent=list.length+" places";$("placeGrid").innerHTML=list.map(p=>`<article class="place"><div class="place-img" style="background-image:url('${p.image}')"><span class="tag">${p.tag} · ${$("month").value}</span></div><div class="place-body"><h3>${p.name}</h3><small>${p.state} · ${p.duration}</small><div class="place-meta"><span>★ ${p.rating}</span><b>${money(p.budget)}</b></div><button data-id="${p.id}">Explore →</button></div></article>`).join("");$("placeGrid").querySelectorAll("button").forEach(b=>b.onclick=()=>openPlace(+b.dataset.id));const s=seasonInfo[$("month").value];document.body.dataset.season=s[3];$("discoverTip").textContent=s[2]+" Check local conditions before departure.";buildAtmosphere()}
function renderSaved(){const saved=JSON.parse(localStorage.getItem("itineraSaved")||"[]");$("savedCount").textContent=saved.length;$("savedGrid").innerHTML=saved.length?saved.map(p=>`<article class="saved-card"><div class="pic" style="background-image:url('${p.image}')"></div><div class="body"><h3>${p.name}</h3><p>${p.state} · ${money(p.budget)} starter</p><button onclick="openPlace(${p.id})">Open place</button></div></article>`).join(""):`<div style="grid-column:1/-1;padding:40px;text-align:center;color:var(--muted);font-size:10px">No saved places yet. Explore the atlas and save your favourites.</div>`}
function renderAtlas(){$("atlasGrid").innerHTML=ITINERA_DATA.map(s=>`<article class="state-card"><h3>${s.state}</h3><p>${s.places.map(x=>x.name).slice(0,4).join(" · ")}</p><button onclick="selectState('${s.state.replace(/'/g,"\\'")}')">Explore state →</button></article>`).join("")}
function selectState(s){$("state").value=s;showView("discover");renderPlaces()}
function openPlace(id){selectedPlace=placeById(id);if(!selectedPlace)return;$("modalPhoto").style.backgroundImage=`url('${selectedPlace.image}')`;$("modalState").textContent=selectedPlace.state.toUpperCase();$("modalTitle").textContent=selectedPlace.name;$("modalDesc").textContent=`Start with a ${selectedPlace.duration.toLowerCase()} ${selectedPlace.tag} trip. ITINERA can turn this place into a day-by-day route with a budget, stay cue, food cue and travel video research.`;$("modalBudget").textContent=money(selectedPlace.budget);$("modalBest").textContent=selectedPlace.best;$("modalStay").textContent=selectedPlace.stay;$("modalFood").textContent=selectedPlace.food;$("modalYT").href=`https://www.youtube.com/results?search_query=${encodeURIComponent(selectedPlace.name+" "+selectedPlace.state+" travel")}`;$("placeModal").classList.add("show")}
function closeModal(){$("placeModal").classList.remove("show")}
$("modalClose").onclick=closeModal;$("placeModal").onclick=e=>{if(e.target.id==="placeModal")closeModal()};
function savePlace(p){let saved=JSON.parse(localStorage.getItem("itineraSaved")||"[]");if(!saved.some(x=>x.id===p.id)){saved.push(p);localStorage.setItem("itineraSaved",JSON.stringify(saved));$("savedCount").textContent=saved.length;toast("Saved "+p.name);}else toast("Already saved.");renderTrips()}
$("modalSave").onclick=()=>selectedPlace&&savePlace(selectedPlace);
$("modalPlanner").onclick=()=>{if(!selectedPlace)return;closeModal();$("planPlace").textContent=selectedPlace.name;$("plannerMeta")?.remove();showView("planner");drawRoadmap()};
function drawRoadmap(){const labels=["Arrival","Explore","Taste","Culture","Relax","Local life","Departure"],icons=["⌖","◒","🍛","✦","☕","⌂","→"];if(!selectedPlace){$("roadmap").innerHTML='<div class="empty-road">Select a destination to generate your roadmap.</div>';return}$("roadmap").innerHTML=`<div class="road-line"></div><div class="nodes">${labels.slice(0,selectedDays).map((x,i)=>`<div class="node"><div class="node-icon">${icons[i]}</div>Day ${i+1}<small>${x}</small></div>`).join("")}</div>`}
for(let i=1;i<=7;i++){let b=document.createElement("button");b.textContent=i+" day"+(i>1?"s":"");if(i===7)b.className="active";b.onclick=()=>{selectedDays=i;document.querySelectorAll("#dayTabs button").forEach(x=>x.classList.remove("active"));b.classList.add("active");drawRoadmap()};$("dayTabs").appendChild(b)}
$("generatePlan").onclick=()=>{if(!selectedPlace){toast("Choose a destination first.");return}drawRoadmap();toast(`${selectedDays}-day ${selectedPlace.name} roadmap created.`)};
$("changePlace").onclick=()=>showView("discover");
$("globalSearch").oninput=()=>{if($("view-discover").classList.contains("active"))renderPlaces()};document.addEventListener("keydown",e=>{if(e.key==="/"){e.preventDefault();$("globalSearch").focus()}if(e.key==="Escape")closeModal()});
$("month").onchange=renderPlaces;$("state").onchange=renderPlaces;$("vibe").onchange=renderPlaces;$("sort").onchange=renderPlaces;$("budget").oninput=renderPlaces;$("nature").onchange=renderPlaces;$("culture").onchange=renderPlaces;$("low").onchange=renderPlaces;
$("clearFilters").onclick=()=>{$("globalSearch").value="";$("state").value="";$("vibe").value="Anything";$("nature").checked=false;$("culture").checked=false;$("low").checked=false;$("budget").value=25000;$("sort").value="match";$("month").value="September";renderPlaces()};
$("notifBtn").onclick=()=>toast("No new travel alerts. Your September dashboard is up to date.");
$("profileBtn").onclick=()=>toast("Traveler profile · local browser mode");
function buildAtmosphere(){const box=$("atmosphere");box.innerHTML="";if(!atmo)return;const s=document.body.dataset.season;if(s==="monsoon"){for(let i=0;i<105;i++){let d=document.createElement("i");d.className="rain-drop"+(i%10===0?" big":"");d.style.left=Math.random()*100+"%";d.style.animationDuration=(.55+Math.random()*.9)+"s";d.style.animationDelay=(-Math.random()*4)+"s";d.style.opacity=.16+Math.random()*.55;box.appendChild(d)}}else if(s==="summer"){for(let i=0;i<22;i++){let d=document.createElement("i");d.className="sun-mote";d.style.left=Math.random()*100+"%";d.style.top=Math.random()*100+"%";d.style.animationDelay=(-Math.random()*8)+"s";box.appendChild(d)}}else{for(let i=0;i<20;i++){let d=document.createElement("i");d.className="leaf";d.textContent=s==="winter"?"❄":"🍂";d.style.left=Math.random()*100+"%";d.style.animationDuration=(6+Math.random()*8)+"s";d.style.animationDelay=(-Math.random()*10)+"s";box.appendChild(d)}}}
$("atmoBtn").onclick=()=>{atmo=!atmo;$("atmoBtn").innerHTML=atmo?"☔ <span>Rain ON</span>":"☔ <span>Rain OFF</span>";buildAtmosphere()};
function toast(msg){const t=$("toast");t.textContent=msg;t.classList.add("show");clearTimeout(window.t);window.t=setTimeout(()=>t.classList.remove("show"),2200)}
renderFeatured();renderCompact();renderTrips();renderCalendar();renderPlaces();